/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
}

repositories {
    mavenLocal()
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    implementation("com.sap.customercheckout:ENV:2.16.2")
    // implementation("org.slf4j.slf4j-log4j12:1.8.0-beta4")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("metcap.CouponsAddon")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
tasks.jar {
    manifest {
        archiveBaseName.set("metcapcoupons")
        archiveFileName.set("metcapcoupons-1.0.jar")
        attributes(
            "pluginName" to "metcap",
            "cashdeskPOSPlugin" to "metcap.CouponsAddon",
            "cashDeskVersions" to "2.0 FP12, 2.0 FP13, 2.0 FP14, 2.0 FP15, 2.0 FP16, 2.0 FP17,2.0 FP18, n/a",
            "version" to "2.14.0",
            "pluginVersion" to "2.14.0"
        )
    }
        
}
